name = "SymbolicIntegration"
uuid = "f4e4f4aa-3f79-40b5-a03c-adbd486f12a6"
authors = ["Mattia Micheletta Merlin"]
version = "1.0.0-DEV"

[deps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Symbolics = "6.40.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
